import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const satoshi = localFont({
  src: "../assets/fonts/Satoshi.ttf",
  variable: "--satoshi",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "STANNUM Game",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="es">
      <body className={`${satoshi.className} antialiased w-full min-h-svh flex flex-col items-center`}>
        {children}
      </body>
    </html>
  );
}
